default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3  # Utilisation de SQLite pour le développement

test:
  <<: *default
  database: db/test.sqlite3  # Utilisation de SQLite pour les tests

production:
  primary:
    <<: *default
    database: test  # Nom de ta base de données PostgreSQL sur Render (ici "test")
    username: <%= ENV['DB_USERNAME'] %>  # Nom d'utilisateur PostgreSQL
    password: <%= ENV['DB_PASSWORD'] %>  # Mot de passe PostgreSQL
    host: <%= ENV['DB_HOST'] %>  # Hôte de ta base de données PostgreSQL sur Render
    port: <%= ENV['DB_PORT'] || 5432 %>  # Port PostgreSQL (généralement 5432)

  cache:
    <<: *default
    database: cache_database_name
    url: <%= ENV['DB_CACHE_URL'] %>

  queue:
    <<: *default
    database: queue_database_name
    url: <%= ENV['DB_QUEUE_URL'] %>

  cable:
    <<: *default
    database: cable_database_name
    url: <%= ENV['DB_CABLE_URL'] %>
